version: '3.1'

services:

  database:
    container_name: authdemo-database
    image: "mysql:8.3.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/mysql

  server:
    container_name: authdemo-server
    restart: on-failure
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - database

volumes:
  database-data:


