version: '3.1'

services:

  database:
    container_name: authdemo-database
    image: "mysql:8.3.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: your-email@example.com
      MAIL_PASSWORD: your-email-password
      MAIL_PROTOCOL: smtp
      MAIL_SMTP_AUTH: true
      MAIL_SMTP_STARTTLS_ENABLE: true
      MAIL_SMTP_STARTTLS_REQUIRED: true
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/mysql

  server:
    container_name: authdemo-server
    restart: on-failure
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - database

volumes:
  database-data:


